apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accounts
    spec:
      containers:
      - image: "${NAMESPACE}/postgresql:${POSTGRESQL_VERSION}"
        name: accounts
        resources: {}
        securityContext:
          runAsUser: 26
          runAsGroup: 26
          fsGroup: 26
        env:
          - name: POSTGRESQL_USER
            value: javad
          - name: POSTGRESQL_PASSWORD
            value: laskdfiwrqwlfiosdf  # Change this to a secure password
          - name: POSTGRESQL_DATABASE
            value: testdb
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust 

status: {}
